### ISSUE TITLE
Simulation error for `next_gen_simulator`

### ISSUE THREAD

**Issue by ebezzam** [LCAV/pyroomacoustics#115]
Ran into some cases where ray tracing and image source model (ISM) approaches break for the new simulator. Possibly due to sources too close to the microphone?

---
Ray tracing breaking example
```python
import numpy as np
import pyroomacoustics as pra

shoebox = pra.ShoeBox(
    [4.232053263716528, 3.9244954007318853, 5.563810437305445],
    materials=pra.Material.make_freq_flat(absorption=0.6965517438548237),
    fs=16000,
    max_order=17,
    ray_tracing=True
)
source_loc = [1.2028020579854695, 2.2980760894630676, 2.0654520390433984]
shoebox.add_source(source_loc)
R = np.array([[1.8062807887952617],
              [2.7793113278109454],
              [1.42966428606882]])
print('mic - source distance : {} m'.format(
    np.sqrt(sum((np.array(source_loc) - np.squeeze(R))**2)))
)
shoebox.add_microphone_array(pra.MicrophoneArray(R, shoebox.fs))
shoebox.compute_rir()
```
Error message
```bash
Traceback (most recent call last):
  File "examples/ray_tracing_breaking.py", line 20, in <module>
    shoebox.compute_rir()
  File "pyroomacoustics/pyroomacoustics/room.py", line 1396, in compute_rir
    n_bins = np.nonzero(self.rt_histograms[m][s][0].sum(axis=0))[0][-1] + 1
IndexError: index -1 is out of bounds for axis 0 with size 0
```

---
ISM breaking example
```python
import numpy as np
import pyroomacoustics as pra

shoebox = pra.ShoeBox(
    [9.29447785567344, 6.529510207957697, 4.4677460263160995],
    materials=pra.Material.make_freq_flat(absorption=0.1675976883006225),
    fs=16000,
    max_order=17
)
source_loc = [5.167674641605016, 4.379726875714017, 2.9190423403507504]
shoebox.add_source(source_loc)
noise_loc = [8.47420884677372, 5.675261722911696, 1.2040578622058364]
shoebox.add_source(noise_loc)
R = np.array([[8.571318246865648],
              [5.799718630723678],
              [1.3702254938278977]])
print('mic - source distance : {} m'.format(
    np.sqrt(sum((np.array(source_loc) - np.squeeze(R))**2)))
)
print('mic - noise distance : {} m'.format(
    np.sqrt(sum((np.array(noise_loc) - np.squeeze(R))**2)))
)
shoebox.add_microphone_array(
    pra.MicrophoneArray(R, shoebox.fs))
shoebox.compute_rir()
```
Error message
```bash
Traceback (most recent call last):
  File "examples/ism_breaking.py", line 25, in <module>
    shoebox.compute_rir()
  File "pyroomacoustics/pyroomacoustics/room.py", line 1433, in compute_rir
    fast_rir_builder(ir_loc, time, alpha, vis, self.fs, fdl)
  File "pyroomacoustics/build_rir.pyx", line 53, in pyroomacoustics.build_rir.fast_rir_builder
    assert min_sample >= 0
AssertionError
```

**Comment by fakufaku** [comment]
Fixed in 92e42db
