### ISSUE TITLE
Installing the repo on docker raises error

### ISSUE THREAD

**Issue by cli0** [LCAV/pyroomacoustics#143]
Im trying to install this repo on a docker image and I get the following error:

```
Collecting pyroomacoustics
  Downloading https://files.pythonhosted.org/packages/aa/8b/d022ceb6ec673299074d20a4fb16e076bce21058edd30153ffd3eb152334/pyroomacoustics-0.3.1.tar.gz (172kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0z9wjfi9/pyroomacoustics/setup.py", line 3, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0z9wjfi9/pyroomacoustics/
The command '/bin/sh -c pip3 install  numpy==1.18.1  tensorflow-gpu==0.12.1  hyperopt  scipy  pandas  tables  attrdict  progressbar  keras  hyperas  librosa  deepspeech==0.4.1  python_speech_features  pyxdg  pydub  mlflow  matplotlib  pyroomacoustics  git' returned a non-zero code: 1
```
Why is numpy failing? I have an exact same setup on a local machine with numpy 1.18.1 where pyroomacoustics was install correctly and fine.

**Comment by fakufaku** [comment]
Hi @cli0 , are you sure numpy is installed before you install pyroomacoustics ? It is hard to provide more help with so little information.

In case that helps, I've managed to run pyroomacoustics in mybinder, which I believe relies on docker for virtualization. You can check it out [here](https://mybinder.org/v2/gh/LCAV/pyroomacoustics/master?filepath=notebooks%2Fpyroomacoustics_demo.ipynb).

I'm closing the issue as it does not seem related to pyroomacoustics, but feel free to keep messaging here or open another issue if needed later.

**Comment by cli0** [comment]
Hi @fakufaku . Yes, I had installed the latest numpy prior to installing pyroomacoustics and the error still happened. It only happens when I try to install it in a virtualized docker image. OS is Ubuntu 18.04.

**Comment by fakufaku** [comment]
I have had some problems whereas the python and pip commands would run in different environments. This can be a problem if you run first `pip install ...` followed by `python setup.py ...`. To make sure that the same `pip` is used, you can run it as `python -m pip install ...`. 

Also, I'm not so familiar with the Docker, but it would certainly help to debug to post your Docker file here.

**Comment by cli0** [comment]
```
FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y \
 build-essential \
 curl \
 apt-utils \
 python \
 python-dev \
 python-pip \
 python3 \
 python3-dev \
 python3-pip \
 swig \
 unzip \
 sox \
 libsox-dev \
 python-pyaudio \
 git \
 wget \
 silversearcher-ag \
 ranger \
 ffmpeg \
 python3-levenshtein \
 python-numpy \
 libcurl3-dev  \
 ca-certificates \
 gcc-6 \
 g++-6 \
 libsox-fmt-mp3 \
 htop \
 nano \
 cmake \
 zlib1g-dev \
 libbz2-dev \
 liblzma-dev \
 locales \
 pkg-config \
 libsox-dev \
 freeglut3-dev \
 libx11-dev \
 libxmu-dev \
 libxi-dev \
 libglu1-mesa \
 libglu1-mesa-dev

RUN DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration

WORKDIR /home/setup/

RUN wget https://github.com/bazelbuild/bazel/releases/download/0.15.0/bazel-0.15.0-installer-linux-x86_64.sh
RUN chmod +x bazel-0.15.0-installer-linux-x86_64.sh
RUN ./bazel-0.15.0-installer-linux-x86_64.sh
RUN rm bazel-0.15.0-installer-linux-x86_64.sh


# Install NVIDIA

#RUN sudo echo "blacklist nouveau" >> /etc/modprobe.d/blacklist-nouveau.conf
#RUN sudo echo "options nouveau modeset=0" >> /etc/modprobe.d/blacklist-nouveau.conf

#RUN add-apt-repository ppa:graphics-drivers
RUN apt-get update
RUN apt install nvidia-driver-390 -y

# Install Python specific packages

RUN pip3 install --upgrade setuptools pip wheel

RUN pip3 install absl-py==0.9.0 \
numpy \
astor==0.8.1 \
attrdict==2.0.1 \
audioread==2.1.8 \
cffi==1.13.2 \
cycler==0.10.0 \
Cython==0.29.14 \
decorator==4.4.1 \
deepspeech==0.4.1 \
gast==0.3.3 \
grpcio==1.26.0 \
h5py==2.10.0 \
joblib==0.14.1 \
Keras-Applications==1.0.8 \
Keras-Preprocessing==1.1.0 \
kiwisolver==1.1.0 \
librosa==0.7.2 \
llvmlite==0.31.0 \
Markdown==3.1.1 \
matplotlib==3.1.2 \
numba==0.47.0 \
numexpr==2.7.1 \
numpy==1.18.1 \
pandas==0.25.3 \
progressbar==2.5 \
protobuf==3.11.2 \
pycparser==2.19 \
pydub==0.23.1 \
pyparsing==2.4.6 \
python-dateutil==2.8.1 \
python-Levenshtein==0.12.0 \
python-speech-features==0.6 \
pytz==2019.3 \
resampy==0.2.2 \
scikit-learn==0.22.1 \
scipy==1.4.1 \
six==1.14.0 \
SoundFile==0.10.3.post1 \
tables==3.6.1 \
tensorboard==1.12 \
tensorflow-gpu==1.12.0 \
Werkzeug==0.16.0 \
pyroomacoustics \

RUN wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda_9.0.176_384.81_linux-run
RUN chmod +x cuda_9.0.176_384.81__linux-run
RUN ./cuda_9.0.176_384.81__linux-run --override
RUN rm cuda_9.0.176_384.81__linux-run

ENTRYPOINT /bin/bash

```
The setup fails when it reaches pyroomacoustics with the error I mentioned in my first post.
