### ISSUE TITLE
"invalid value encountered in double_scalars" when importing a STL donut file

### ISSUE THREAD

**Issue by opasquetdotfr** [LCAV/pyroomacoustics#195]
Hello !

I am importing STL files in the form of donuts.
I get the following error:
`XXX/XXX/Library/Python/2.7/lib/python/site-packages/pyroomacoustics/room.py:539: RuntimeWarning: invalid value encountered in double_scalars
  t0 = ((2 * np.log(2)) / fpcv) ** (1.0 / 3.0)
Traceback (most recent call last):
  File "/XXX/XXX/Documents/code/pyroomacoustics/my_second_test_12_GH.py", line 155, in <module>
    room.simulate()
  File "/XXX/XXX/Library/Python/2.7/lib/python/site-packages/pyroomacoustics/room.py", line 1971, in simulate
    self.compute_rir()
  File "/XXX/XXX/Library/Python/2.7/lib/python/site-packages/pyroomacoustics/room.py", line 1823, in compute_rir
    seq = sequence_generation(volume_room, N / self.fs, self.c, self.fs)
  File "/XXX/XXX/Library/Python/2.7/lib/python/site-packages/pyroomacoustics/room.py", line 555, in sequence_generation
    seq = np.zeros(indices[-1] + 1)
ValueError: negative dimensions are not allowed
`

I wonder if this is linked with the given order of the mesh faces. I am using a similar code as the one found in the examples:

`the_mesh = mesh.Mesh.from_file(path_to_musis_stl_file)
ntriang, nvec, npts = the_mesh.vectors.shape
`

`walls = []
for w in range(ntriang):
        walls.append(
                     pra.wall_factory(
                                      the_mesh.vectors[w].T / size_reduc_factor,
                                      material.energy_absorption["coeffs"],
                                      material.scattering["coeffs"],
                                      )
        )
`

**Comment by fakufaku** [comment]
Hi, the problem could be that the wall normal are pointing in the wrong direction. In pyroomacoustics, we make the assumption that the normals are pointing *outside* of the room.
I think that if the normals are reversed, then the volume will come out negative.

**Comment by fakufaku** [comment]
Closing this due to lack of activity.
