### ISSUE TITLE
About Error "ImportError: cannot import name libroom"

### ISSUE THREAD

**Issue by tyauyade** [LCAV/pyroomacoustics#198]
Hi

The following error has occurred.
==================================================================================
File "<stdin>", line 7, in <module> File "pyroomacoustics/__init__.py", line 120, in <module> from . import libroom as libroom ImportError: cannot import name libroom
==================================================================================

I think packages'download is succes because the folder named "pyroomacoustics" is created.
Do you have solution and reason about this problem.

#enviroment
=========================================
version: python 3.7.6(64bit)
package: pyroomacoustics-0.4.2-cp37-cp37m-win_amd64.whl 
OS: Windows
Other:I'm using Anaconda.
=========================================

If there is lack of inromation, please ask me.

Sincerely,

**Comment by fakufaku** [comment]
Hi @tyauyade , thanks for reporting this. It looks like the package was not properly compiled. How did you install the package ? If you install with pip, there should be a precompiled package for windows available.

**Comment by dolphinjpn** [comment]
Hi fakufaku, thank you very much for your comments.
I got same error, "ImportError: cannot import name libroom" in window's environment when I installed pyroomacoustics with pip, following after I installed Anaconda3-2019.10-Windows-x86_64. Could you tell how to precompile the package of pyroomacoustics for windows? Thank you very much in advance.

**Comment by fakufaku** [comment]
Hi @dolphinjpn , which version of python are you using ? The package from pip for windows is already a precompiled for python up to 3.7. I will work on adding pre-compiled binaries for python 3.8 and 3.9 very soon!
Another thing to pay attention is that if you try to run the examples from the git repo root directly, python might pick up the local `pyroomacoustics` folder before the one installed from pip.

**Comment by dolphinjpn** [comment]
Hi fakufaku, thank you very much for your quick response.  The version of python I installed is 3.7.4, which is including in Anaconda3-2019.10-Windows-x86_64. Could you tell me how to install pyroomacoustics into windows' environment correctly?
I always got the error :  "ImportError: cannot import name libroom". your help will be much appreciated.

**Comment by dolphinjpn** [comment]
Hi fakufaku，I tried 3.7.6 on windows 10, and it works. However when I installed it on windows 7 with same steps, the error 'ImportError: cannot import name libroom' still occurs. If you know how to cope with it, please tell me. your help will be much appreciated.

**Comment by fakufaku** [comment]
@dolphinjpn I am not a windows user myself, so I am not sure about the differences between windows 7 or 10 when it comes to Python.
Could you please provide a little bit more detail, like the series of commands you used to to install the package as well as the command you use to run the script ? Also, have you cloned the github repo too, or are you trying to run one of your scripts ?

**Comment by dolphinjpn** [comment]
Hi fakufaku，Thank you so much again for your quick response.
In order to install pyroomacoustics, first I downloaded Anaconda3-2020.02-Windows-x86_64.exe, which includes Python 3.7.6 and installed it into windows 7. Then I ran 'Anaconda powershell prompt(Anaconda3)' from the windows' start button. and the prompt shows "(base) PS C:\Users\John>". Using 'pip install pyroomacoustics', I installed the pyroomacoustics, the prompt showing "Successfully installed pyroomacoustics-0.4.2". At this time, no error occurs. Entering python environment, I got the following error when I input 'import pyroomacoustics as pa':

>>>import pyroomacoustics as pa
Traceback (most recent call last):
   File "stdin", line 1, in <module>
   File "C:\Users\john\anacodda3\lib\site-packages\pyroomacoustics\__init__.py", line 120, in <module>
  from . import libroom as libroom
ImportError: DLL load failed: module cannot be found.
>>>

I have not used the github tool and no scripts are used. If you have any idea to fix the error, pls tell me.
Thank you again.

John

**Comment by fakufaku** [comment]
Thank you for the information! I think I now know what the problem is. After re-checking the [wheel files](https://pypi.org/project/pyroomacoustics/#files) on pypi, I noticed that the recent releases were compiled on amd64 processors, which I had not noticed. Since it seems you are using an x86_64 machine, the binary wheels do not exist.
I don't have a windows machine available to produce the new wheels, so the quickest solution is probably to compile the package yourself. For this, you will need Visual Studio C++ 14.00. We have some instructions [https://github.com/LCAV/pyroomacoustics/blob/master/CONTRIBUTING.rst#develop-locally].
Apologize for the extra effort needed!

**Comment by dolphinjpn** [comment]
Fortunitaly I have VC++ 14.00 in my pc. Actually I was a C++ programmer, but am a new comer for python. So I try to compile pyroomacoustics following your instruction. Though it appears many warnings during compiling, finally the 'dll's seem to be created. They are work. 
Thank you very much for your help.

**Comment by fakufaku** [comment]
It is great that you could solve it! Thank you for your patience! I have renamed the issue to keep track of the problem.

**Comment by dolphinjpn** [comment]
Thank you very much for your help. I need to learn more about python and pyroomacoustics. Could you introduce me some suitable python books for a C++ programmer if possible ?

**Comment by fakufaku** [comment]
I'm not sure about something specific for C++ programmers, but the [official python tutorial](https://docs.python.org/3/tutorial/) seems to be very good! I also heard good things about [Fluent Python](https://www.amazon.co.jp/-/en/Luciano-Ramalho/dp/1491946008).

**Comment by dolphinjpn** [comment]
Great book！ I have bought it. Thank you.
