### ISSUE TITLE
Assertion Error: pyroomacoustics.build_rir.fast_rir_builder

### ISSUE THREAD

**Issue by moonlightSong** [LCAV/pyroomacoustics#205]
File "...\Anaconda3\lib\site-packages\pyroomacoustics\soundsource.py", line 254, in get_rir
    fast_rir_builder(ir, time, alpha, visibility.astype(np.int32), Fs, fdl)
  File "pyroomacoustics\build_rir.pyx", line 53, in pyroomacoustics.build_rir.fast_rir_builder
AssertionError

Hi there,
Any idea what might lead to the above error message?

**Comment by fakufaku** [comment]
Hi @moonlightSong , thanks for reporting the error. Can you please provide the OS, python version, platform, and how you installed the package ? Thanks!

**Comment by moonlightSong** [comment]
@fakufaku  Thanks for resply. 
The OS is  Windows 10. The python version is python 3.7.  The platform is conda 4.9.2. Install is by pip.
The error message is given by pyroomacoustics 0.4.2. For some setup it works and for some it prints the error.  In the later case, pyroomacoustics 0.3.1 fails quietly.

**Comment by fakufaku** [comment]
Thank you very much for providing the extra information.
This seems to be an error with the cython code that builds the RIR from the information about the echo delays and amplitudes. I think this may happen if the source and the microphones are too close (which would be a bug of course, since all cases should be covered). Is it possible for you to check if the failing cases have the smallest distance between sources and microphones ?

**Comment by moonlightSong** [comment]
In https://github.com/LCAV/pyroomacoustics/blob/869ebc38cfe6a04e4f7b0e71a79101ab345dbc54/pyroomacoustics/room.py#L1761
at this line
https://github.com/LCAV/pyroomacoustics/blob/869ebc38cfe6a04e4f7b0e71a79101ab345dbc54/pyroomacoustics/room.py#L1848
the time is adjusted. 
When use room.compute_rir() directly instead of rewrite it like posted above, the code doesn't complain. 

In
https://github.com/LCAV/pyroomacoustics/blob/5d25cbe15fbcfddb43f16cb7a8ce5b7567f1e922/pyroomacoustics/soundsource.py#L220
time is not adjusted.

so it seems that get_rir() is causing the problem because it didn't adjust the time.

**Comment by fakufaku** [comment]
Sorry for coming back so late to this issue. Indeed, the code in soundsource is something left-over from the previous implementation of the Room class.
In recent version of pyroomacoustics, the preferred way to get the room impulse response is via the Room class, see [the doc here](https://pyroomacoustics.readthedocs.io/en/pypi-release/pyroomacoustics.room.html#create-the-room-impulse-response).

**Comment by moonlightSong** [comment]
No worries. But if there are 2 places where the rir can be obtained, it is
better that they are consistent, otherwise it is error-prone.

**Comment by c-ma13** [comment]
Thank you so much. You really helped me. 
I add the same time delay when using get_rir(), and looks like it worked when generating WHAMR! dataset.

> In
> 
> https://github.com/LCAV/pyroomacoustics/blob/869ebc38cfe6a04e4f7b0e71a79101ab345dbc54/pyroomacoustics/room.py#L1761
> 
> 
> at this line
> https://github.com/LCAV/pyroomacoustics/blob/869ebc38cfe6a04e4f7b0e71a79101ab345dbc54/pyroomacoustics/room.py#L1848
> 
> 
> the time is adjusted.
> When use room.compute_rir() directly instead of rewrite it like posted above, the code doesn't complain.
> In
> 
> https://github.com/LCAV/pyroomacoustics/blob/5d25cbe15fbcfddb43f16cb7a8ce5b7567f1e922/pyroomacoustics/soundsource.py#L220
> 
> 
> time is not adjusted.
> so it seems that get_rir() is causing the problem because it didn't adjust the time.

**Comment by fakufaku** [comment]
Hi @SilentIcyMoon 
To generate whamr! using the original script you need to use an old version of pyroomacoustics.
According to the `requirements.txt` provided with the generation scripts, you need `0.3.1`.

```
pyroomacoustics==0.3.1
SoundFile==0.10.3.post1
pandas==1.1.2
scipy==1.5.2
numpy==1.19.1
pyloudnorm==0.1.0
```

**Comment by SilentIcyMoon** [comment]
Hi @fakufaku 
Thank you so much for your information! 
I followed your suggestion to re-install the required modules. And I met the following new error:
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd
C-extension libroom unavailable. Falling back to pure python
C-extension libroom unavailable. Falling back to pure python
Traceback (most recent call last):
File "create_wham_from_scratch.py", line 167, in
create_wham(args.wsj0_root, args.wham_noise_root, args.output_dir)
File "create_wham_from_scratch.py", line 71, in create_wham
room.generate_rirs()
File "/home/joschi/Downloads/Data/wham_noise/whamr_scripts/wham_room.py", line 52, in generate_rirs
self.compute_rir()
File "/home/joschi/Downloads/Data/wham_noise/whamr_scripts/wham_room.py", line 44, in compute_rir
h.append(source.get_rir(mic, self.visibility[s][m], self.fs, self.t0)[:self.max_rir_len])
File "/home/joschi/Dokumente/espnet-master/tools/anaconda/envs/myenv/lib/python3.8/site-packages/pyroomacoustics/soundsource.py", line 233, in get_rir
fast_rir_builder(ir, time, alpha, visibility, Fs, fdl)
File "pyroomacoustics/build_rir.pyx", line 14, in pyroomacoustics.build_rir.fast_rir_builder
ValueError: Buffer dtype mismatch, expected 'int' but got 'bool'

And I further solved the above issue by changing the versions of some modules, now I share the modules's versions I used now:
python==3.10.14
cython==0.29.30
pyroomacoustics==0.3.1
SoundFile==0.10.3.post1
pandas==2.2.2 (new)
scipy==1.13.1 (new)
numpy==1.22.4 (new)

I hope these information will be helpful for someone who are facing the same issue.
In addition, a useful link can refer:
https://github.com/asteroid-team/asteroid/pull/613

**Comment by fakufaku** [comment]
@SilentIcyMoon thanks for reporting back! The version is pretty old so I am not surprised there are some problems with the compilation 😭 
Happy you solved it and it is good to have the information here now! 🤗
