### ISSUE TITLE
ImportError: ~/libroom.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

### ISSUE THREAD

**Issue by cDavidAlumno** [LCAV/pyroomacoustics#314]
Hi. I have a situation to use pyromacoustics in the base environment of Ananconda. I leave information that may be useful (Thanks in advance):

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

conda 4.12.0

(base) my_user:~$ pip install pyroomacoustics
Collecting pyroomacoustics
  Using cached pyroomacoustics-0.7.3-cp39-cp39-linux_x86_64.whl
Requirement already satisfied: numpy>=1.13.0 in ./anaconda3/lib/python3.9/site-packages (from pyroomacoustics) (1.22.4)
Requirement already satisfied: pybind11>=2.2 in ./anaconda3/lib/python3.9/site-packages (from pyroomacoustics) (2.10.3)
Requirement already satisfied: Cython in ./anaconda3/lib/python3.9/site-packages (from pyroomacoustics) (0.29.28)
Requirement already satisfied: scipy>=0.18.0 in ./anaconda3/lib/python3.9/site-packages (from pyroomacoustics) (1.7.3)
Installing collected packages: pyroomacoustics
Successfully installed pyroomacoustics-0.7.3

(base) my_user:~$ python
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.

I have the following error when importing pyroomacoustics to the anaconda base environment:

>>> import pyroomacoustics as pra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/anaconda3/lib/python3.9/site-packages/pyroomacoustics/__init__.py", line 124, in <module>
    from . import libroom as libroom
ImportError: /home/david/anaconda3/lib/python3.9/site-packages/pyroomacoustics/libroom.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr10_M_releaseEv

**Comment by fakufaku** [comment]
This seems to be a known issues with pybind11 in some environments.
https://github.com/pybind/pybind11/issues/3623

Apparently, some people could solve it by upgrading their compiler version, Ubuntu, or anaconda.
